[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
opika_voting_system = "5MTTqsGoj5JjXeyEoA8MCSFgDN3HMjJo8q9E6oxuLatk"
[programs.devnet]
opika_voting_system = "5FNAvGjh53rUH2cNJps5CqYmTeuBNAv8m6zaKLqFoA3m"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
# wallet = "/Users/apple/.config/solana/id.json"
wallet = "scripts/main_wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
